1025 quiet prepareuninstall
opentap/opentap pull request #1026
Opened 2023-02-21 09:22 UTC by alnlarsen

This logs the 'Tried to prepareuninstall package', but there was nothing to do' at the debug level instead of info level.

Closes #1025

2023-02-21 10:59 UTC, AsgerIversen commented on Package/Installer.cs
> +                        else if (res == ActionResult.Quiet) log.Debug(msg);
Can we just make this always debug?

2023-02-22 10:07 UTC, AsgerIversen approved these changes

2023-02-22 10:28 UTC, AsgerIversen requested changes
Nice and simple. It fails a test though.

2023-02-22 11:30 UTC, alnlarsen commented
Argh, that's what we get for making unittests that depend on stdout.

2023-02-22 13:13 UTC, merged