1045 repo 4.0
opentap/opentap pull request #1087
Opened 2023-04-13 13:41 UTC by alnlarsen

Use repo client and target repo 4.0 API to support authentication

Closes #1045

2023-04-18 07:57 UTC, StefanHolst requested changes
Looks great, just some minor comments.

2023-04-18 07:57 UTC, StefanHolst commented on Engine/Authentication/AuthenticationSettings.cs
> +                        // TODO: fix todo
Seems unhelpful

2023-04-18 07:57 UTC, StefanHolst commented on Package/Repositories/HttpPackageRepository.cs
>          private VersionSpecifier MinRepoVersion = new VersionSpecifier(3, 0, 0, "", "", VersionMatchBehavior.AnyPrerelease | VersionMatchBehavior.Compatible);
Is this needed anymore?

2023-04-18 07:57 UTC, StefanHolst commented on Package/IPackageRepository.cs
> +                            packages(directory: ""/Packages/"", distinctName:true" +
Should we just use the query api from the client?

2023-04-18 07:57 UTC, StefanHolst commented on Package/Image/PackageDependencyQuery.cs
> +                packages(directory: ""/Packages/"", version: ""__VERSION__"", type:""tappackage"", os:""__OS__"", architecture:""__ARCH__"" __NAME_QUERY__) {
Should we use the repoclient here as well?

2023-04-18 07:57 UTC, StefanHolst commented on Package/Repositories/HttpPackageRepository.cs
> +        private void Auth()
Should we call it something like, AttachAuthentication?

2023-04-18 07:57 UTC, StefanHolst commented on Package/Repositories/HttpPackageRepository.cs
> +                ["type"] = @class,
Type and class are not the same. It should just be class

2023-04-18 07:57 UTC, StefanHolst commented on Package/Repositories/HttpPackageRepository.cs
> +        public string QueryGraphQL(string query) => downloadPackagesString($"/3.1/query", query, "application/json", "application/json");
Could we add obsolete attribute and remove this in 9.22? If so, could we also do this for the method above

2023-04-20 10:35 UTC, StefanHolst approved these changes
Looks good

2023-04-20 15:00 UTC, AsgerIversen approved these changes

2023-04-20 15:01 UTC, merged