1223 OpenTapPackageReference Token: Fix
opentap/opentap pull request #1224
Opened 2023-08-30 09:27 UTC by rmadsen-ks

- Added support for setting tokens from csproj files.
- Added cli action set-auth-token (Browsable(false)) for now to set the user token,

2023-08-31 09:16 UTC, alnlarsen commented
This is really cool. Much nicer than having to install Cloud Drive and completing a login flow.

Can we improve the usability a bit for `set-auth-token`? If I want to login in to the repository 'https://test-automation.pw.keysight.com/api/packages', I have to strip the https scheme and /api/packages subpath, otherwise I get his error: `Domain should only be the host part of a URI and not a full absolute URI.`

I think it would be more natural for users to be able to just use the repository URL instead of having to know the specifics of how OpenTAP compares URIs.

2023-08-31 09:23 UTC, alnlarsen requested changes
This is really good

2023-08-31 09:23 UTC, alnlarsen commented on Package/PackageActions/SetUserToken.cs
> +    [Browsable(false)]
Can we make this browsable?

2023-08-31 09:23 UTC, alnlarsen commented on Package/PackageActions/SetUserToken.cs
> +        static readonly TraceSource log = Log.CreateSource("set-auto-token");
```suggestion
        static readonly TraceSource log = Log.CreateSource("set-auth-token");
```

2023-08-31 09:23 UTC, alnlarsen commented on sdk/OpenTap.Sdk.MSBuild/InstallOpenTapPackages.cs
> +        bool ProcessAuthTokens()
I feel like this is encouraing people to put user tokens directly in their .csproj / check it into source control. I know we will use environment variables for this, but I don't feel great about it.

2023-08-31 09:23 UTC, alnlarsen commented on Package/PackageActions/SetUserToken.cs
> +    public class SetUserToken : ICliAction
Can we call it `login` so it is a single verb like the other package actions? `create`, `list` etc.

2023-08-31 09:23 UTC, alnlarsen commented on Package/PackageActions/SetUserToken.cs
> +        public string Domain { get; set; }
Rename this to repository and copy-paste the description / flags from the other package actions

2023-09-01 07:58 UTC, rmadsen-ks commented
@alnlarsen, please check it again.

2023-09-01 08:04 UTC, alnlarsen approved these changes
Looks good!

2023-09-01 08:12 UTC, merged