1166 PackageReference to drive bug: Fix issue with paths being trimmed
opentap/opentap pull request #1227
Opened 2023-09-06 11:16 UTC by rmadsen-ks

- Also added that drive-letter + '':' (D:) is a valid identifier on Windows. This could be useful for people storing packages on e.g USB or network drives.

2023-09-06 13:23 UTC, alnlarsen requested changes
There appears to be one minor issue

2023-09-06 13:23 UTC, alnlarsen commented on Package/Repositories/FilePackageRepository.cs
> +            }
This turns `C:\` into `C:\\`

2023-09-07 11:27 UTC, rmadsen-ks commented on Package/Repositories/FilePackageRepository.cs
> +            }
This was fixed.

2023-09-07 11:27 UTC, rmadsen-ks commented on Package.UnitTests/FilePackageRepoTest.cs
> +        [TestCase("C:\\")]
Yes, but it is a bit har to make a general test for it since \ (like /) can mean many things.

2023-09-07 14:58 UTC, alnlarsen requested changes
It looks like you added the same test twice

2023-09-07 14:58 UTC, alnlarsen commented on Package.UnitTests/FilePackageRepoTest.cs
> +        [TestCase("/", null)]
The "/" case is here twice. Did you mean to put "\\\\" or remove it?

2023-09-08 07:37 UTC, alnlarsen approved these changes
Looks good!

2023-09-08 07:45 UTC, merged