Update plugin enumeration logic
opentap/opentap pull request #1335
Opened 2023-11-07 14:58 UTC by alnlarsen

2023-11-10 20:21 UTC, alan-copeland-keysight commented
It seems closer, but its pulling in some of the Python plugins that I **reference/inherit** from, rather than just the ones I **implement**.

Anything from opentap.py should be from the Python package, not my package. 

Do you agree @alnlarsen / @rmadsen-ks ?

```
<?xml version="1.0" encoding="utf-8"?>
<Package Date="11/10/2023 18:54:13" Name="Operator UI Python" Version="0.1.0-rc+aa3ee757" Architecture="AnyCPU" OS="Windows" xmlns="http://opentap.io/schemas/package">
  <Hash>J80CxwLGdpMjWPd5Y2yp1naIOyI</Hash>
  <Description>Operator UI implemented in Python. Connects to a KS8500 Runner and allows an operator to run tests.
        <Prerequisites> Python (&gt;3.7) </Prerequisites><Organisation>Keysight Technologies</Organisation></Description>
  <Dependencies>
    <PackageDependency Package="OpenTAP" Version="^9.22.1" />
    <PackageDependency Package="Cloud Drive" Version="^0.2.0" />
    <PackageDependency Package="Python" Version="^3.0.2" />
    <PackageDependency Package="Runner" Version="^1.5.2" />
  </Dependencies>
  <Owner>OpenTAP</Owner>
  <SourceUrl>https://github.com/opentap/Operator-UI-Python</SourceUrl>
  <SourceLicense>MIT</SourceLicense>
  <Files>
    <File Path="Packages/Operator UI Python/requirements.txt">
      <PythonRequirements></PythonRequirements>
      <Hash>7195799080803ABE285A656E529363F11DE25EE8</Hash>
    </File>
    <File Path="Packages/Operator UI Python/cli.py">
      <Plugins>
        <Plugin Type="OpenTap.py.Rule" BaseType="">
          <Name>Rule</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyTestStep" BaseType="Test Step">
          <Name>PyTestStep</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyDut" BaseType="Dut">
          <Name>PyDut</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyInstrument" BaseType="Instrument">
          <Name>PyInstrument</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyResultListener" BaseType="Result Listener">
          <Name>PyResultListener</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="Operator UI Python.settings.OperatorUIPythonSettings" BaseType="Component Settings">
          <Name>Operator UI Python</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Settings for Operator UI Python</Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Start" BaseType="">
          <Name>start</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Launch the Operator UI</Description>
          <Collapsed>false</Collapsed>
          <Groups>
            <String>operator</String>
          </Groups>
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Stop" BaseType="">
          <Name>stop</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Stop the Operator UI</Description>
          <Collapsed>false</Collapsed>
          <Groups>
            <String>operator</String>
          </Groups>
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Settings" BaseType="">
          <Name>settings</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Settings for the Operator UI</Description>
          <Collapsed>false</Collapsed>
          <Groups>
            <String>operator</String>
          </Groups>
        </Plugin>
        <Plugin Type="OpenTap.py.Rule" BaseType="">
          <Name>Rule</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyTestStep" BaseType="Test Step">
          <Name>PyTestStep</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyDut" BaseType="Dut">
          <Name>PyDut</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyInstrument" BaseType="Instrument">
          <Name>PyInstrument</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyResultListener" BaseType="Result Listener">
          <Name>PyResultListener</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.Rule" BaseType="">
          <Name>Rule</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyTestStep" BaseType="Test Step">
          <Name>PyTestStep</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyDut" BaseType="Dut">
          <Name>PyDut</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyInstrument" BaseType="Instrument">
          <Name>PyInstrument</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="OpenTap.py.PyResultListener" BaseType="Result Listener">
          <Name>PyResultListener</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description></Description>
          <Collapsed>false</Collapsed>
          <Groups />
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Start" BaseType="">
          <Name>start</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Launch the Operator UI</Description>
          <Collapsed>false</Collapsed>
          <Groups>
            <String>operator</String>
          </Groups>
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Stop" BaseType="">
          <Name>stop</Name>
          <Order>-10000</Order>
          <Browsable>true</Browsable>
          <Description>Stop the Operator UI</Description>
          <Collapsed>false</Collapsed>
          <Groups>
            <String>operator</String>
          </Groups>
        </Plugin>
        <Plugin Type="Operator UI Python.cli.CliAction_Settings" BaseType="">
          <Name>sett [...]

2023-11-17 12:45 UTC, rmadsen-ks requested changes
Make sure this still works for .net types.

2023-11-17 12:45 UTC, rmadsen-ks commented on Package/TestPlanPackageDependencySerializer.cs
> +                                break;
```suggestion
                            if (src != null){
                                usedSources.Add(src)
                                break;
                                }
```

2023-11-20 14:16 UTC, AsgerIversen submitted a review, later dismissed

2023-11-20 14:59 UTC, Denrask approved these changes

2023-11-20 15:00 UTC, merged