1786 layout improvements
opentap/opentap pull request #1787
Opened 2024-10-09 21:09 UTC by rmadsen-ks

Close #1786

2024-10-10 07:31 UTC, alnlarsen requested changes
See comments. Let's discuss!

2024-10-11 11:30 UTC, rmadsen-ks commented on Engine/UserInput.cs
> +        public int MinWidth { get; set; } = -1;
I dont know. What is the default unit of MinWidth? We dont write the unit for height either.

2024-10-11 11:30 UTC, rmadsen-ks commented on Engine/UserInput.cs
> +        WordWrapping = 8
I dont think so. We should default to no wrapping.

2024-10-14 11:36 UTC, alnlarsen approved these changes
This looks great!

2024-10-21 10:52 UTC, merged