314 Change casing of UserID dir
opentap/opentap pull request #466
Opened 2022-03-16 15:51 UTC by alnlarsen

Closes #314

2022-03-16 16:10 UTC, rmadsen-ks requested changes
It seems that there are other places where this folder is being used.
```
./docker/Linux/Dockerfile:26:RUN echo 11111111-1111-1111-1111-111111111111 > /root/.local/share/OpenTAP/OpenTapGeneratedId
./docker/Windows/Dockerfile:10:RUN echo 11111111-1111-1111-1111-111111111111 > C:\Users\ContainerAdministrator\AppData\Local\OpenTAP\OpenTapGeneratedId
./Package/Repositories/HttpPackageRepository.cs:100:            var idPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.Create), "OpenTap", "OpenTapGeneratedId");
./Package.UnitTests/PackageManagerTests.cs:64:            var idPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.Create), "OpenTAP", "OpenTapGeneratedId");
```
maybe we should consolidate it?

2022-03-21 11:11 UTC, rmadsen-ks requested changes
There are multiple references to OpenTapGeneratedId. Should these also be changed?

2022-05-02 12:00 UTC, alnlarsen commented
Yes!

2022-05-02 12:02 UTC, rmadsen-ks approved these changes
Looks good!

2022-05-02 12:34 UTC, rmadsen-ks commented
For the record, the reason we change OpenTAP -> OpenTap is that OpenTAP is only used for an installation id, whicle OpenTap contains a PackageCache. Hence if we change that we risk that the users leak that amount of harddrive space.

2022-05-11 11:06 UTC, rmadsen-ks approved these changes
Looks great!

2022-05-11 11:27 UTC, rmadsen-ks commented
Docker does no like this:

```
INFO[0043] args: [-c echo 11111111-1111-1111-1111-111111111111 > /root/.local/share/OpenTap/OpenTapGeneratedId] 
INFO[0043] Running: [/bin/sh -c echo 11111111-1111-1111-1111-111111111111 > /root/.local/share/OpenTap/OpenTapGeneratedId] 
/bin/sh: 1: cannot create /root/.local/share/OpenTap/OpenTapGeneratedId: Directory nonexistent
```

2022-05-11 13:36 UTC, rmadsen-ks approved these changes
Looks great.

2022-05-11 13:36 UTC, merged