Update CONTRIBUTING.md
opentap/opentap pull request #490
Opened 2022-03-25 15:30 UTC by bilzinho

Clarified language regarding individual vs. corporate contribution, minor grammar and diction edits, added reference link in last paragragh.  Cf. Issue #455

2022-03-28 21:37 UTC, bdirenzo-keysight approved these changes

2022-04-07 02:30 UTC, bdirenzo-keysight commented
@AsgerIversen FYI this is what you were looking to get reviewed

2022-08-03 13:02 UTC, AsgerIversen requested changes
Thanks @bilzinho. Looks good. Just one small comment..

2022-08-08 21:25 UTC, bilzinho commented on CONTRIBUTING.md
> +Thank you for your interest in contributing to the OpenTAP project. Contributions include feature enhancement requests, issue reporting, bug fixes, etc. as well as plugins and other new code.
Asger - I completely agree and have created a new version / update to the file that removed the language you note and adds a sentence on the fact that plugins are not governed by the CLA.

2022-08-10 22:34 UTC, bdirenzo-keysight commented
@AsgerIversen I noticed you were merging doc stuff. This should also be good to go.

2022-08-11 06:43 UTC, AsgerIversen approved these changes

2022-08-11 06:46 UTC, merged