Create lock directory if it is missing.
opentap/opentap pull request #530
Opened 2022-05-02 08:59 UTC by alnlarsen

flock would throw an exception if the directory containing the lock file was missing.

Closes #528

2022-05-02 11:29 UTC, rmadsen-ks requested changes
I can see that we use this inside  LockingPackageAction when setting --target. Maybe it would be better to ensure that the directory exists there and throw an exception if it is not the case inside FileLock?

I think it might be a bit surprising if FileLock also creates directories.

2022-05-02 11:40 UTC, alnlarsen commented
Hmm, I agree, an error would be expected in this case.

2022-05-02 18:54 UTC, rmadsen-ks approved these changes
this looks good

2022-05-11 11:08 UTC, rmadsen-ks approved these changes
Looks great!

2022-05-11 11:08 UTC, merged