317 invalidate non alpha numeric chars for identifiers
opentap/opentap pull request #536
Opened 2022-05-05 14:44 UTC by frederikja163

Invalidates non alpha numeric chars for `tap sdk new xx` names if the name will be used for a C# identifier, since C# identifiers dont allow most non alpha numeric chars.
Closes: #317 
## Testing
Added sweep variables to the *test-sdk-templates* tap testplan to test that non alpha numeric chars fail.

2022-05-09 13:02 UTC, rmadsen-ks submitted a review, later dismissed
Seems to work well!

2022-05-11 19:16 UTC, AsgerIversen requested changes
Thanks @frederikja163 . Can we also allow underscores?

2022-05-12 08:17 UTC, frederikja163 commented
Underscores are now allowed, and a sweep parameter has been added to test if they are valid aswell.

2022-05-12 08:30 UTC, rmadsen-ks approved these changes
Looks great!

2022-05-18 10:09 UTC, AsgerIversen approved these changes

2022-05-18 10:10 UTC, merged