541 type data attributes gets unintentionally inherited
opentap/opentap pull request #542
Opened 2022-05-06 13:15 UTC by rmadsen-ks

2022-05-11 14:43 UTC, alnlarsen approved these changes
Looks good.

2022-05-17 08:44 UTC, AsgerIversen requested changes
Looks like there is an issue with a unit test.

```
Failed TestSerializeInheritTestPlan [4 ms]
  Error Message:
   System.ArgumentException : Cannot add test step of type DelayStep as a root test step (must be nested).
  Stack Trace:
     at OpenTap.TestStepList.InsertItem(Int32 index, ITestStep item) in D:\a\opentap\opentap\Engine\TestStepList.cs:line 271
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at OpenTap.Engine.UnitTests.XmlTextAttributeTest.TestSerializeInheritTestPlan() in D:\a\opentap\opentap\Engine.UnitTests\SerializerTest.cs:line 2597
  Passed TestSerializeProcessStepWithNullDefaultValue [5 ms]
```

2022-05-18 07:47 UTC, rmadsen-ks commented
Fixed the unit test. I think this proves that this change is slightly breaking as people who have previously been relying on inheriting AllowAnyChild may get into trouble now.

2022-05-18 10:06 UTC, AsgerIversen approved these changes

2022-05-18 10:06 UTC, merged