112 give better warnings when attempting to upgrade OpenTAP with <OpenTapPackageReference>
opentap/opentap pull request #568
Opened 2022-05-11 12:14 UTC by alnlarsen

This adds a specific warning for the special case where another version of OpenTAP is specified with

<OpenTapPackageReference Include='OpenTAP' Version=' ... />

This also adds some mechanisms to make it easier to test MSBuild actions without compiling actual projects (which is tested by TestWindowsPlan anyway)

Closes #112

2022-05-17 14:53 UTC, rmadsen-ks approved these changes

2022-05-18 12:37 UTC, AsgerIversen requested changes

2022-05-18 12:37 UTC, AsgerIversen commented on sdk/OpenTap.Sdk.MSBuild/OpenTapImageInstaller.cs
> +    public interface IImageDeployer
This is just here to be able to mock things, right? Could we make it internal, and use `InternalsVisibleTo("OpenTap.Package.UnitTests")` ? 

... same for the new public property on `InstallOpenTapPackages`

2022-05-19 09:50 UTC, AsgerIversen approved these changes

2022-05-19 10:25 UTC, merged