520 i type data source
opentap/opentap pull request #569
Opened 2022-05-12 10:21 UTC by rmadsen-ks

First implementation of ITypeDataSource

Closes #520

2022-05-19 14:46 UTC, alnlarsen requested changes

2022-05-19 14:46 UTC, alnlarsen commented on Engine/Reflection/PluginOrderAttribute.cs
> +                var lut = new Dictionary<object, PluginOrderAttribute>();
lut == lookup table? can we get a better name?

2022-05-19 14:46 UTC, alnlarsen commented on Engine/TestStep.cs
> +                    //Log.Warning("Could not parse test plan file specified version {0} of step '{1}' as a semantic version, but version {2} is installed, compatibility issues may occur.", value, Nam
why was this commented?

2022-05-20 13:32 UTC, alnlarsen approved these changes
I think this looks fine now, though I didn't actually test it.

2022-05-23 09:29 UTC, AsgerIversen requested changes
APIs looks good. I have one small comment.

@rmadsen-ks can you test a bit by using this in Python plugin/KS8400 and then merge if that works out?

2022-05-23 11:06 UTC, rmadsen-ks commented on Package/CreatePackage/Package.cs
> +                                    throw new Exception($"Assembly {candidateAsm} version is null");
I think it is technically impossible for the version to be null under normal circumstances. The only reason I added this here is that OpenTap.Utils.Compatible throws a NullReferenceExeption exception if Version is null and I wanted to be easier to spot why this issue occurs.

2022-05-23 11:09 UTC, AsgerIversen approved these changes

2022-05-23 11:15 UTC, merged