739 don't include Package.Dependencies element when serializing `PackageVersion[]`
opentap/opentap pull request #740
Opened 2022-08-09 07:27 UTC by alnlarsen

Closes #739

2022-08-09 08:42 UTC, rmadsen-ks requested changes
``var writePackageDependencies = Serializer.GetUsedTypes().Any(t => t.DescendsTo(typeof(TestPlan)));```

We don't want to only do this when the type is TestPlan.

If you dont want the behavior in some specific case, why not just add the option to disable the package dependency check?

2022-08-10 11:01 UTC, rmadsen-ks requested changes
OK, I understand this now. Looks good, but I had a couple of suggestions.

2022-08-10 11:01 UTC, rmadsen-ks commented on Package/PackageDefinitionSerializerPlugin.cs
> +            if (expectedType.IsA(typeof(PackageDef)) == false
can you modify the xml comment of this method to be more specific?

2022-08-10 12:27 UTC, alnlarsen commented
I have added some comments and improved the license element bug fix. Please take another look :)

2022-08-12 10:22 UTC, rmadsen-ks approved these changes
Looks good!

2022-08-12 11:20 UTC, merged