Make valuetypes constructable
opentap/opentap pull request #779
Opened 2022-09-02 13:23 UTC by alnlarsen

Mark valuetypes as constructable in the plugin searcher
Make typedata treat valuetypes as constructable
Add unittest to verify the fix
CLoses #610

2022-09-05 13:08 UTC, rmadsen-ks requested changes
It seem it doesnt build, but otherwise it makes sense.

2022-09-05 13:08 UTC, rmadsen-ks commented on Engine/PluginSearcher.cs
> +                    break;
```suggestion
```

2022-09-05 13:08 UTC, rmadsen-ks commented on Engine/PluginSearcher.cs
> +                    break;
```suggestion
```

2022-09-06 07:59 UTC, alnlarsen commented
It looks like the valuetype check threw in some cases. I never saw that locally, so I'm glad it happened in the pipelines!

2022-09-06 08:38 UTC, rmadsen-ks requested changes
Testing this with "tap benchmark startup --iterations 100" gives this:

this branch:
694.24 ms

main branch:
685.25 ms

So it does seem like this is somewhat slower than what was before, although I had expected it to actually be faster. Maybe we could add some caching of which types are value types to avoid iterating too much over common base types?

2022-09-06 11:38 UTC, alnlarsen commented
Thanks a lot for the benchmarks. I will try to squeeze a bit more performance out of this.

2022-09-06 13:05 UTC, alnlarsen commented
I ran the benchmarks again:

this branch:
718.74 ms

main branch: 
782.49 ms

Can you please verify these results?

2022-09-07 14:48 UTC, rmadsen-ks approved these changes
Looks good

2022-09-09 10:57 UTC, AsgerIversen commented
@rmadsen-ks according to a comment from Dennis in the issue, this could also be fixed by https://github.com/opentap/opentap/issues/607. Is that correct, and if so, are we not doing that?

2022-09-09 11:06 UTC, alnlarsen commented
@AsgerIversen I don't see the relation between those two issues. There are constructable value types that aren't always preloaded which this solution handles.

2022-09-12 07:48 UTC, merged