902 Add iteration display to SweepParameterRangeStep
opentap/opentap pull request #943
Opened 2022-12-19 09:41 UTC by frederikja163

closes #902 

Add an iteration property to SweepParameterRangeStep

2022-12-30 15:41 UTC, rmadsen-ks submitted a review, later dismissed
Works perfectly!

2023-01-03 11:04 UTC, AsgerIversen requested changes
Nice addition. 

I think there is a good point with the `OutputAvailability.BeforeRun` that @cpetku uses in [the patch](https://github.com/opentap/opentap/issues/902#issuecomment-1322617603) in the issue. 

@alnlarsen, @rmadsen-ks what do you say we add that to the output here and in SweepParameterStep?

Without `OutputAvailability.BeforeRun`:

![image](https://user-images.githubusercontent.com/20689829/210344773-1149ea16-7b6f-416f-a55b-56a90a5fde90.png)

With:

![image](https://user-images.githubusercontent.com/20689829/210344250-cb6a9fce-806d-4548-ac6b-54d12505281b.png)

2023-02-03 12:23 UTC, frederikja163 commented
@AsgerIversen I have tagged both outputs as available BeforeRun

2023-02-09 10:45 UTC, AsgerIversen approved these changes

2023-02-09 10:46 UTC, merged