doc: add prepare uninstall documentation
opentap/opentap pull request #959
Opened 2023-01-12 13:56 UTC by alnlarsen

This adds documentation for the new PrepareUninstall verb

Closes #957

2023-01-16 12:30 UTC, AsgerIversen requested changes
Looks good. One small typo

2023-01-16 12:30 UTC, AsgerIversen commented on doc/Developer Guide/Plugin Packaging and Versioning/Readme.md
> +The above example is an excerpt of a plugin.xml file that defines a plugin that includes a test plan to verify that the steps it provides are working correctly, and a binary executable for generating
Looks like a "typo" that `and a CLI action that it needs to run when it is uninstalled` is now here twice

2023-01-25 15:30 UTC, alnlarsen commented
I ended up changing the whole sentence to an itemized list because it was getting out of hand.

2023-02-09 08:28 UTC, AsgerIversen approved these changes

2023-02-09 08:28 UTC, merged