970 search async memory leak fix
opentap/opentap pull request #978
Opened 2023-01-23 22:24 UTC by rmadsen-ks

The formally fixes #970. 

Although this should generally not be an issue, this can save a few MBs of memory from time to time.

Another solution could have been to move to conditional weak tables, but they use reference equality instead of object equality which make it a not so great general solution.

Close #970

2023-01-24 09:57 UTC, alnlarsen commented on Shared/Cache.cs
> +            dict = dict.Add(key, value);
Call ClearCheck here?

2023-01-24 09:59 UTC, alnlarsen requested changes
Looks good. I didn't test it yet. Can we add a ClearCheck to the Add method?

2023-01-24 13:39 UTC, alnlarsen approved these changes
I reproduced the issue and verified the fix. Looks good.

2023-02-07 12:48 UTC, AsgerIversen requested changes
@rmadsen-ks / @alnlarsen would it be possible to use our Memorizer class and avoid introducing another Caching utility class?

2023-02-08 11:46 UTC, rmadsen-ks commented
> @rmadsen-ks / @alnlarsen would it be possible to use our Memorizer class and avoid introducing another Caching utility class?

I think we could, but in that case we would have to introduce extra functionality to the memorizer class. We need something that can automatically invalidate everything in the memorizer and then clear that. This is a bit different from what it currently does.

I would say that introducing this new Cache class is less risky than trying to add the extra functionality to a class which is already quite complicated.

2023-02-09 08:12 UTC, AsgerIversen approved these changes

2023-02-09 08:13 UTC, merged